### ISSUE TITLE
Build failed with xmlschema v3

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/grantami-bomanalytics#409]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The dependabot PR failed with xmlschema v3. We should investigate the issue and fix.

### 📝 Steps to reproduce

See https://github.com/ansys/grantami-bomanalytics/pull/403

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Failed in CI

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
Failed in CI
```

**Comment by ludovicsteinbach** [comment]
Correctly deserialized (provided the gbt namespace is declared):
```
<MIProcessReference>
    <gbt:dbKey >MI_Restricted_Substances</gbt:dbKey>
    <gbt:recordGUID >baa6c95b-ff0e-4811-9120-92717ee15bda</gbt:recordGUID>
</MIProcessReference>
```

Not correctly deserialized:
```
<MIProcessReference>
    <dbKey xmlns="http://www.grantadesign.com/12/05/GrantaBaseTypes">MI_Restricted_Substances</dbKey>
    <recordGUID xmlns="http://www.grantadesign.com/12/05/GrantaBaseTypes">baa6c95b-ff0e-4811-9120-92717ee15bda</recordGUID>
</MIProcessReference>
```

**Comment by da1910** [comment]
Done in #452
