### ISSUE TITLE
Remove versionadded directives

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/grantami-bomanalytics#464]
https://github.com/ansys/grantami-bomanalytics/blob/0e283eda033a99e0fe6d001c859ca86a6cf96908/src/ansys/grantami/bomanalytics/indicators.py#L376

It's not been used for all additions and it doesn't make sense to keep it forever

**Comment by Andy-Grigg** [comment]
I think these directives are useful, and I'm happy to keep this in as long as we commit to including them for all additions
