### ISSUE TITLE
Add license check pre-commit hook

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/grantami-bomanalytics#484]
Add the license check pre-commit hook.

This failed the first time we tried to add it, so it may need to be run in a debugging mode to figure out what's going wrong.

**Comment by da1910** [comment]
We're stuck waiting for a new release of ansys/pre-commit-hooks but that looks imminent. The bug was fixed in https://github.com/ansys/pre-commit-hooks/pull/163
