### ISSUE TITLE
Replicate label workflow from jobqueue repository

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/grantami-bomanalytics#486]
The recordlists repository includes a workflow to automatically label PRs. We should replicate that in this repository.

https://github.com/ansys/grantami-recordlists/blob/main/.github/workflows/label.yml

**Comment by da1910** [comment]
I'm not sure if I'm missing something here but that workflow already exists - see https://github.com/ansys/grantami-bomanalytics/blob/main/.github/workflows/label.yml 

https://github.com/ansys/grantami-bomanalytics/actions/runs/8713012276

**Comment by Andy-Grigg** [comment]
Nope, I don;t think you are missing anything. We can close this as done.
